#define SFX_B_DED	0
#define SFX_B_JUMP	1
#define SFX_B_SHOOT	2
#define SFX_B_STEP	3
#define MOD_WORLD1	0
#define MOD_WORLD2	1
#define MOD_WORLD3	2
#define MOD_WORLD4	3
#define MOD_THEME	4
#define MSL_NSONGS	5
#define MSL_NSAMPS	109
#define MSL_BANKSIZE	114
