#define SFX_M_LEVELCOMPLETE	0
#define SFX_S_PAGE	1
#define SFX_M_SAVE	2
#define SFX_M_LOAD	3
#define SFX_M_CONFIRM	4
#define SFX_B_EXPLODE	5
#define SFX_B_TRAMPOLINE	6
#define SFX_B_HURT	7
#define SFX_B_DED	8
#define SFX_B_JUMP	9
#define SFX_B_SHOOT	10
#define SFX_B_STEP	11
#define SFX_M_SELECT	12
#define MOD_WORLD1	0
#define MOD_WORLD2	1
#define MOD_WORLD3	2
#define MOD_WORLD4	3
#define MOD_THEME	4
#define MOD_STORY	5
#define MSL_NSONGS	6
#define MSL_NSAMPS	144
#define MSL_BANKSIZE	150
