#define SFX_S_PAGE	0
#define SFX_M_SAVE	1
#define SFX_M_LOAD	2
#define SFX_M_CONFIRM	3
#define SFX_B_EXPLODE	4
#define SFX_B_TRAMPOLINE	5
#define SFX_B_HURT	6
#define SFX_B_DED	7
#define SFX_B_JUMP	8
#define SFX_B_SHOOT	9
#define SFX_B_STEP	10
#define SFX_M_SELECT	11
#define MOD_WORLD1	0
#define MOD_WORLD2	1
#define MOD_WORLD3	2
#define MOD_WORLD4	3
#define MOD_THEME	4
#define MSL_NSONGS	5
#define MSL_NSAMPS	139
#define MSL_BANKSIZE	144
